Reengineered placeParts in background.js
ahmadileham/Deepnest pull request #7
Opened 2024-11-17 10:56 UTC by sulaimanmhashim

**The Addressed Issue**
--------------------------------

The original placeParts function was overly complex, difficult to read, and hard to maintain. Key issues included:

1. Monolithic Design: The function handled multiple responsibilities, such as part rotation, placement evaluation, and fitness calculation, all in a single block of code (around 377 loc).

2. Redundancy: Repeated operations like bounding box calculations and polygon manipulations increased inefficiency.

3. Limited Configurability: Hardcoded logic (e.g., gravity direction) made the function inflexible.

4. Error Handling: Insufficient mechanisms to handle edge cases (e.g., unplaceable parts) cleanly.

5. Lack of Modularization: The lack of smaller reusable components made debugging and testing difficult.

**What Have Been Reengineered**
----------------------------------

The function was broken down into smaller, reusable components with clear responsibilities. Specific changes include:

1. Decomposed the Functionality: Extracted reusable logic into helper functions:
- prepareParts: Rotates and initializes parts.
- placePartsOnSheet: Handles part placement on a single sheet.
- findBestPlacement: Finds the optimal placement for a part.
- evaluatePlacement: Evaluates placement quality based on configurable criteria.
- calculateUnplacedPenalty: Penalizes unplaced parts.
- Separated fitness calculation, caching, and placement evaluation into distinct functions.

2. Introduced Generalization: Made the placement evaluation adaptable to various strategies (e.g., gravity-based or bounding-box-based placement).

3. Optimized Operations: Reduced redundancy by caching results where applicable (e.g., clip cache for precomputed no-fit poygons). Consolidated repeated geometry operations into single-use helper functions.

4. Improved Error Handling: Added checks and defaults to gracefully handle cases like unplaceable parts.

5. Enhanced Readability: Streamlined nested loops and complex conditionals.
Added meaningful function names and comments for clarity.

**Reengineering Strategy or Approach Used**
-----

The reengineering process was guided by the following strategies:

1. Refactoring:
Broke down the original function into smaller units with single responsibilities.
Reorganized logic for clarity and maintainability.

2. Modularization:
Abstracted core operations into reusable helper functions (e.g., evaluatePlacement, calculateShiftVector).

3. Separation of Concerns:
Separated unrelated concerns like progress notifications, geometry manipulation, and placement evaluation.

4. Parameterization:
Introduced configurability for logic like placement types (gravity, box, etc.), reducing hardcoded dependencies.

5. Efficiency Improvements:
Optimized frequent operations (e.g., bounding box calculations, merging lines) to reduce computational overhead.

6. Error Handling and Resilience:
Added robust checks for cases like missing polygons or empty placements.

**Impact of Changes**
------------

1. Maintainability:
The function is now easier to read, debug, and extend due to clear separation of logic.
Developers can focus on individual parts of the function without affecting others.

2. Scalability:
The reengineered function supports multiple placement strategies and can easily accommodate new features like advanced heuristics.

3. Performance:
Optimized operations reduce redundant calculations, improving efficiency, especially for large datasets.

4. Adaptability:
Generalized logic allows for easy configuration and reuse in different contexts.

5. Error Handling:
Unplaceable parts and other edge cases are now handled gracefully, reducing the likelihood of runtime errors.

6. Code Reusability:
Smaller, reusable helper functions (e.g., prepareParts, findBestPlacement) can be utilized across other parts of the system.

2024-11-29 09:02 UTC, suhadaudd11 commented
Well done @sulaimanmhashim, would like to see the usage in the system later. And the re-engeneering strategy explained are not related with what we learned

2024-11-29 09:03 UTC, suhadaudd11 commented
Please resolve the conflict and then you proceed to merge

2024-12-02 11:06 UTC, Dexus requested changes

2024-12-02 11:06 UTC, Dexus commented on main/background.js
> +    if (config.placementType === 'gravity') {
missing box, while box has default bounds added without multiply the width with 2

2024-12-22 15:26 UTC, merged